import { Command, Message } from "./types";

export const DEFAULT_MESSAGES: Message[] = [
  { id: 1, username: 'OwlWatcherAlice', message: 'Those baby owls are adorable!', color: 'purple' },
  { id: 2, username: 'FeatherFanBob', message: 'Look at that owl stretching its wings!', color: 'blue' },
  { id: 3, username: 'HootHootCarol', message: 'The owls are so peaceful to watch.', color: 'red' },
  { id: 4, username: 'NocturnalDave', message: 'I could watch these owls all night!', color: 'purple' },
  { id: 5, username: 'TwilightEve', message: 'Has anyone seen the owl pair in the corner?', color: 'blue' },
  { id: 6, username: 'PerchedFrank', message: 'The way they blink is mesmerizing!', color: 'red' },
  { id: 7, username: 'OwlNestGrace', message: 'I love the variety of owls on this stream.', color: 'purple' },
  { id: 8, username: 'SilentWingsHeidi', message: 'The owls are so calm tonight.', color: 'blue' },
  { id: 9, username: 'NightOwlIvan', message: 'When is the next owl feeding time?', color: 'red' },
  { id: 10, username: 'HootingHank', message: 'Those owls are really active tonight!', color: 'purple' },
  { id: 11, username: 'FeatheredFriend', message: 'I love seeing the owls interact with each other.', color: 'blue' },
  { id: 12, username: 'WiseOldOwl', message: 'Can you spot the owl with the unique markings?', color: 'red' },
  { id: 13, username: 'MidnightMarauder', message: 'The stream is so calming after a long day.', color: 'purple' },
  { id: 14, username: 'DuskTillDawn', message: 'I’m fascinated by the different owl calls.', color: 'blue' },
  { id: 15, username: 'WingspanWill', message: 'Look at that owl flying across the screen!', color: 'red' },
  { id: 16, username: 'OwlEnthusiast', message: 'This stream is perfect for relaxing.', color: 'purple' },
  { id: 17, username: 'NocturnalNina', message: 'I think I just saw a rare owl species!', color: 'blue' },
  { id: 18, username: 'EagleEyeEd', message: 'The detail in the owls’ feathers is amazing.', color: 'red' },
  { id: 19, username: 'TwilightTom', message: 'Love the way the owls look at the camera.', color: 'purple' },
  { id: 20, username: 'OwlsInTheWild', message: 'So many different types of owls here.', color: 'blue' },
  { id: 21, username: 'MoonlightMaddie', message: 'I could watch these owls for hours.', color: 'red' },
  { id: 22, username: 'DawnWatcherDan', message: 'The owls seem so relaxed right now.', color: 'purple' },
  { id: 23, username: 'StarlitSally', message: 'I’m loving the owl families on this stream.', color: 'blue' },
  { id: 24, username: 'OwlGazerGeorge', message: 'That owl perched on the branch is so cute!', color: 'red' },
  { id: 25, username: 'HootsAndHugs', message: 'The owl’s head turns so smoothly.', color: 'purple' },
  { id: 26, username: 'QuietNightNina', message: 'I love the sound of the owls hooting softly.', color: 'blue' },
  { id: 27, username: 'MoonlitMike', message: 'Such a soothing stream to end the day.', color: 'red' },
  { id: 28, username: 'FeatheredFanatic', message: 'The owls are so interesting to watch.', color: 'purple' },
  { id: 29, username: 'HootMasterHank', message: 'That owl looks so wise!', color: 'blue' },
  { id: 30, username: 'DuskDiva', message: 'The owl pairs are so adorable.', color: 'red' },
  { id: 31, username: 'SereneStream', message: 'The owls are so captivating to watch.', color: 'purple' },
  { id: 32, username: 'OwlyOllie', message: 'Does anyone know if there’s a rare owl species here?', color: 'blue' },
  { id: 33, username: 'NighthawkNate', message: 'The owl’s eyes are so expressive.', color: 'red' },
  { id: 34, username: 'WingsOfNight', message: 'I love the way the owls react to the camera.', color: 'purple' },
  { id: 35, username: 'FeatherFanJo', message: 'That owl’s wing span is incredible!', color: 'blue' },
  { id: 36, username: 'MoonlitMarty', message: 'The stream is perfect for relaxation.', color: 'red' }
];

export const EXTRA_MESSAGES: Message[] = [
  { id: 9000, username: 'OwlWatcherAlice', message: 'Those baby owls are adorable!', color: 'purple' },
  { id: 9001, username: 'FeatherFanBob', message: 'Look at that owl stretching its wings!', color: 'blue' },
  { id: 9002, username: 'HootHootCarol', message: 'The owls are so peaceful to watch.', color: 'red' },
  { id: 9003, username: 'NocturnalDave', message: 'I could watch these owls all night!', color: 'purple' },
  { id: 9004, username: 'TwilightEve', message: 'Has anyone seen the owl pair in the corner?', color: 'blue' },
  { id: 9005, username: 'PerchedFrank', message: 'The way they blink is mesmerizing!', color: 'red' },
  { id: 9006, username: 'OwlNestGrace', message: 'I love the variety of owls on this stream.', color: 'purple' },
  { id: 9007, username: 'SilentWingsHeidi', message: 'The owls are so calm tonight.', color: 'blue' },
  { id: 9008, username: 'NightOwlIvan', message: 'When is the next owl feeding time?', color: 'red' },
  { id: 9009, username: 'HootingHank', message: 'Those owls are really active tonight!', color: 'purple' },
  { id: 9010, username: 'FeatheredFriend', message: 'I love seeing the owls interact with each other.', color: 'blue' },
  { id: 9011, username: 'WiseOldOwl', message: 'Can you spot the owl with the unique markings?', color: 'red' },
  { id: 9012, username: 'MidnightMarauder', message: 'The stream is so calming after a long day.', color: 'purple' },
  { id: 9013, username: 'DuskTillDawn', message: 'I’m fascinated by the different owl calls.', color: 'blue' },
  { id: 9014, username: 'WingspanWill', message: 'Look at that owl flying across the screen!', color: 'red' },
  { id: 9015, username: 'OwlEnthusiast', message: 'This stream is perfect for relaxing.', color: 'purple' },
  { id: 9016, username: 'NocturnalNina', message: 'I think I just saw a rare owl species!', color: 'blue' },
  { id: 9017, username: 'EagleEyeEd', message: 'The detail in the owls’ feathers is amazing.', color: 'red' },
  { id: 9018, username: 'TwilightTom', message: 'Love the way the owls look at the camera.', color: 'purple' },
  { id: 9019, username: 'OwlsInTheWild', message: 'So many different types of owls here.', color: 'blue' },
  { id: 9020, username: 'MoonlightMaddie', message: 'I could watch these owls for hours.', color: 'red' },
  { id: 9021, username: 'DawnWatcherDan', message: 'The owls seem so relaxed right now.', color: 'purple' },
  { id: 9022, username: 'StarlitSally', message: 'I’m loving the owl families on this stream.', color: 'blue' },
  { id: 9023, username: 'OwlGazerGeorge', message: 'That owl perched on the branch is so cute!', color: 'red' },
  { id: 9024, username: 'HootsAndHugs', message: 'The owl’s head turns so smoothly.', color: 'purple' },
  { id: 9025, username: 'QuietNightNina', message: 'I love the sound of the owls hooting softly.', color: 'blue' },
  { id: 9026, username: 'MoonlitMike', message: 'Such a soothing stream to end the day.', color: 'red' },
  { id: 9027, username: 'FeatheredFanatic', message: 'The owls are so interesting to watch.', color: 'purple' },
  { id: 9028, username: 'HootMasterHank', message: 'That owl looks so wise!', color: 'blue' },
  { id: 9029, username: 'DuskDiva', message: 'The owl pairs are so adorable.', color: 'red' },
  { id: 9030, username: 'SereneStream', message: 'The owls are so captivating to watch.', color: 'purple' },
  { id: 9031, username: 'OwlyOllie', message: 'Does anyone know if there’s a rare owl species here?', color: 'blue' },
  { id: 9032, username: 'NighthawkNate', message: 'The owl’s eyes are so expressive.', color: 'red' },
  { id: 9033, username: 'WingsOfNight', message: 'I love the way the owls react to the camera.', color: 'purple' },
  { id: 9034, username: 'FeatherFanJo', message: 'That owl’s wing span is incredible!', color: 'blue' },
  { id: 9035, username: 'MoonlitMarty', message: 'The stream is perfect for relaxation.', color: 'red' },
  { id: 9036, username: 'OwlSnoozerSam', message: 'Look at that owl napping so peacefully.', color: 'purple' },
  { id: 9037, username: 'FeatherFiendFinn', message: 'Did anyone else notice the owl with the broken wing?', color: 'blue' },
  { id: 9038, username: 'HootsterHannah', message: 'I love watching the owls’ different hunting techniques.', color: 'red' },
  { id: 9039, username: 'GazingGordon', message: 'That owl’s head turns a full 360 degrees!', color: 'purple' },
  { id: 9040, username: 'NocturnalNancy', message: 'The owls are so graceful in flight.', color: 'blue' },
  { id: 9041, username: 'MysteriousMitch', message: 'That one owl looks like it’s about to swoop down!', color: 'red' },
  { id: 9042, username: 'TwilightTina', message: 'The owl’s large eyes are so striking.', color: 'purple' },
  { id: 9043, username: 'SilentSally', message: 'So many owls gathered in one place!', color: 'blue' },
  { id: 9044, username: 'FeatherFreakFrank', message: 'That owl’s wingspan is massive!', color: 'red' },
  { id: 9045, username: 'GazingGina', message: 'I wonder where that owl is headed?', color: 'purple' },
  { id: 9046, username: 'HootHoundHarry', message: 'That owl is so attentive to its surroundings.', color: 'blue' },
  { id: 9047, username: 'OwlDreamerDaisy', message: 'The way the owls interact with the camera is fascinating.', color: 'red' },
  { id: 9048, username: 'NocturnalNate', message: 'I could watch these owls all day long.', color: 'purple' },
  { id: 9049, username: 'MoonlightMaya', message: 'Those owls are so expressive!', color: 'blue' },
  { id: 9050, username: 'FeatheredFreddie', message: 'The way the owls ruffle their feathers is so cute.', color: 'red' },
  { id: 9051, username: 'HootMasterMia', message: 'The owls’ hoots are so soothing.', color: 'purple' },
  { id: 9052, username: 'TwilightTroy', message: 'I love how the owls seem to respond to the camera.', color: 'blue' },
  { id: 9053, username: 'WingspanWendy', message: 'The owls’ flying patterns are mesmerizing.', color: 'red' },
  { id: 9054, username: 'OwlWatchWill', message: 'That owl looks so regal perched on the branch.', color: 'purple' },
  { id: 9055, username: 'FeatheredFiona', message: 'The details on the owls’ feathers are amazing.', color: 'blue' },
  { id: 9056, username: 'NocturnalNico', message: 'I’m fascinated by the owl’s night vision.', color: 'red' },
  { id: 9057, username: 'MoonlitMel', message: 'The owls’ movements are so fluid.', color: 'purple' },
  { id: 9058, username: 'StarlightSteve', message: 'The stream is so calming to watch before bed.', color: 'blue' },
  { id: 9059, username: 'FeatherFanaticFrankie', message: 'The way the owls look at each other is adorable.', color: 'red' },
  { id: 9060, username: 'OwlsInAction', message: 'Look at the owl swoop down with precision!', color: 'purple' },
  { id: 9061, username: 'TwilightTravis', message: 'I can’t get enough of these owl streams.', color: 'blue' },
  { id: 9062, username: 'MoonlightMaggie', message: 'The different owl species are fascinating.', color: 'red' },
  { id: 9063, username: 'FeatheredFelicity', message: 'The owls’ soft hoots are so calming.', color: 'purple' },
  { id: 9064, username: 'NocturnalNick', message: 'The owls seem so curious about the camera.', color: 'blue' },
  { id: 9065, username: 'OwlObserverOlivia', message: 'The owls’ eyes are so captivating.', color: 'red' },
  { id: 9066, username: 'HootsAndHoots', message: 'The owl families are so sweet.', color: 'purple' },
  { id: 9067, username: 'GazingGareth', message: 'I love the contrast between the owls and the night sky.', color: 'blue' },
  { id: 9068, username: 'FeatheredFloyd', message: 'The stream is a perfect way to relax.', color: 'red' },
  { id: 9069, username: 'MoonlitMandy', message: 'The way the owls react to the lighting is interesting.', color: 'purple' },
  { id: 9070, username: 'StarlitStan', message: 'I’m amazed by how many owls are on this stream.', color: 'blue' },
  { id: 9071, username: 'FeatheredFarmer', message: 'The way the owls interact is so charming.', color: 'red' },
  { id: 9072, username: 'OwlsAndWings', message: 'The stream is so relaxing after a long day.', color: 'purple' },
  { id: 9073, username: 'HootHoundHannah', message: 'I’m loving the variety of owl calls.', color: 'blue' },
  { id: 9074, username: 'FeatherFanaticFelicity', message: 'The detail in the owls’ feathers is incredible.', color: 'red' },
  { id: 9075, username: 'NocturnalNora', message: 'The owls’ expressions are so diverse.', color: 'purple' },
  { id: 9076, username: 'MoonlightMason', message: 'The way the owls fly is so graceful.', color: 'blue' },
  { id: 9077, username: 'FeatheredFred', message: 'The owls’ eyes are so mesmerizing.', color: 'red' },
  { id: 9078, username: 'HootHootHolly', message: 'The different types of owls are fascinating.', color: 'purple' },
  { id: 9079, username: 'StarlitSteve', message: 'The owls’ interactions are so soothing.', color: 'blue' },
  { id: 9080, username: 'MoonlitMila', message: 'The way the owls blink is so charming.', color: 'red' }
];


export const COMMANDS: Command[] = [
  { name: 'block', type: 'username', description: 'Block a user from interacting with you on Twitch' },
  { name: 'unblock', type: 'username', description: 'Remove a user from your block list' },
  { name: 'color', type: 'color', description: 'Change your username color, i.e. blue, green, etc.' },
  { name: 'gift', type: 'quantity', description: 'Gift a specified number of Subs to the community.' },
  { name: 'help', type: 'command', description: 'Get detailed infromation on using a chat command.' },
  { name: 'mods', type: 'none', description: 'Display a list of moderators for this channel.' },
  { name: 'vips', type: 'none', description: 'Display a list of VIPs for this channel.' },
  { name: 'vote', type: 'index', description: 'Vote in the active poll on the given channel.' }
]


